//This code is generated by firebase

import { initializeApp } from "firebase/app";
import { getDatabase } from "firebase/database";

function StartFirebase() {

    const firebaseConfig = {
        apiKey: "AIzaSyAgF9Tb8QaKhPjX8zqlh_kC-vB6Jw-ZNlQ",
        authDomain: "motiondetection3-85340.firebaseapp.com",
        databaseURL: "https://motiondetection3-85340-default-rtdb.firebaseio.com",
        projectId: "motiondetection3-85340",
        storageBucket: "motiondetection3-85340.appspot.com",
        messagingSenderId: "599856859231",
        appId: "1:599856859231:web:8556dba3dda30eeddff3ea",
        measurementId: "G-KGG1Y5MHTP"
    };

    // Initialize Firebase
    const firebaseApp = initializeApp(firebaseConfig);
    return getDatabase(firebaseApp);
}

export default StartFirebase;